---
deployment:
  tasks:
    - /bin/cp -n .env.staging .env 2>/dev/null || true
    - /bin/chmod 755 . admin api database storage 2>/dev/null || true
    - /bin/chmod 644 .htaccess index.html .env 2>/dev/null || true
