-- ============================================================================
-- EXAMVERSE migration v7 — teacher question authoring with admin approval
--
-- Teachers are their own account type (never an upgrade from a student).
-- They submit questions, which stay invisible to students until an admin
-- approves them.
-- ============================================================================

-- 1. Teacher becomes a first-class account type alongside student and creator.
ALTER TABLE `users`
    MODIFY COLUMN `user_type` ENUM('student','creator','teacher') NOT NULL DEFAULT 'student';

-- 2. Questions gain an author and a review trail.
--    author_user_id NULL = authored by staff or generated by AI.
ALTER TABLE `questions`
    ADD COLUMN `author_user_id` INT NULL AFTER `topic_id`;

ALTER TABLE `questions`
    ADD COLUMN `reviewed_by` INT NULL AFTER `status`;

ALTER TABLE `questions`
    ADD COLUMN `reviewed_at` DATETIME NULL AFTER `reviewed_by`;

ALTER TABLE `questions`
    ADD COLUMN `rejection_reason` VARCHAR(500) NULL AFTER `reviewed_at`;

-- 3. A rejected state, so a declined submission is distinguishable from a draft.
ALTER TABLE `questions`
    MODIFY COLUMN `status` ENUM('draft','review','published','rejected') DEFAULT 'published';

ALTER TABLE `questions`
    ADD CONSTRAINT `fk_questions_author`
    FOREIGN KEY (`author_user_id`) REFERENCES `users`(`id`) ON DELETE SET NULL;

ALTER TABLE `questions`
    ADD CONSTRAINT `fk_questions_reviewer`
    FOREIGN KEY (`reviewed_by`) REFERENCES `admins`(`id`) ON DELETE SET NULL;

-- 4. Indexes for the two hot paths: a teacher's own list, and the review queue.
ALTER TABLE `questions`
    ADD INDEX `idx_questions_author` (`author_user_id`, `status`);

ALTER TABLE `questions`
    ADD INDEX `idx_questions_review_queue` (`status`, `created_at`);

-- 5. Teacher profile: display name and specialisation shown in the review queue.
CREATE TABLE IF NOT EXISTS `teacher_profiles` (
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT NOT NULL UNIQUE,
    `display_name` VARCHAR(150) NOT NULL,
    `qualification` VARCHAR(255) NULL,
    `specialisation` VARCHAR(255) NULL,
    `bio` TEXT NULL,
    `questions_submitted` INT NOT NULL DEFAULT 0,
    `questions_approved` INT NOT NULL DEFAULT 0,
    `questions_rejected` INT NOT NULL DEFAULT 0,
    `status` ENUM('active','suspended') NOT NULL DEFAULT 'active',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
